fn main() {
    #[cfg(target_os = "windows")]
    windows::build!(
        Windows::Devices::Bluetooth::GenericAttributeProfile::{
            GattCharacteristic,
            GattCharacteristicProperties,
            GattCharacteristicsResult,
            GattClientCharacteristicConfigurationDescriptorValue,
            GattCommunicationStatus,
            GattDeviceService,
            GattDeviceServicesResult,
            GattReadResult,
            GattValueChangedEventArgs,
            GattWriteOption,
        },
        Windows::Devices::Bluetooth::Advertisement::*,
        Windows::Devices::Bluetooth::{
            BluetoothConnectionStatus,
            BluetoothLEDevice,
            BluetoothCacheMode,
        },
        Windows::Devices::Radios::{
            Radio,
            RadioKind
        },
        Windows::Foundation::{
            DateTime,
            EventRegistrationToken,
            IAsyncOperation,
            IReference,
            TimeSpan,
            TypedEventHandler,
        },
        Windows::Foundation::Collections::{
            IVector,
            IVectorView,
        },
        Windows::Storage::Streams::{
            DataReader,
            DataWriter,
            IBuffer,
        },
    );
}
