fn main() {
    #[cfg(target_os = "windows")]
    windows::build!(
        windows::devices::bluetooth::generic_attribute_profile::{
            GattCharacteristic,
            GattCharacteristicProperties,
            GattCharacteristicsResult,
            GattClientCharacteristicConfigurationDescriptorValue,
            GattCommunicationStatus,
            GattDeviceService,
            GattDeviceServicesResult,
            GattReadResult,
            GattValueChangedEventArgs,
            GattWriteOption,
        },
        windows::devices::bluetooth::advertisement::*,
        windows::devices::bluetooth::{
            BluetoothConnectionStatus,
            BluetoothLEDevice,
        },
        windows::devices::radios::{
            Radio,
            RadioKind
        },
        windows::foundation::{
            EventRegistrationToken,
            IAsyncOperation,
            TypedEventHandler
        },
        windows::foundation::collections::IVector,
        windows::storage::streams::{
            DataReader,
            DataWriter,
            IBuffer,
        },
    );
}
