plugins {
    id 'com.android.library'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.nonpolynomial.btleplug.android'
    compileSdk 34

    defaultConfig {
        minSdk 24
        versionCode 1
        versionName '0.7.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}

tasks.register('testJar', Jar) {
    archiveBaseName = 'btleplug-jni'
    from compileDebugJavaWithJavac.destinationDirectory
    destinationDirectory = file("$buildDir/libs")
    dependsOn 'compileDebugJavaWithJavac'
}
