// This code was autogenerated with dbus-codegen-rust, see https://github.com/diwic/dbus-rs

use dbus as dbus;
use dbus::arg;

pub trait OrgFreedesktopDBusIntrospectable {
    type Err;
    fn introspect(&self) -> Result<String, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgFreedesktopDBusIntrospectable for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn introspect(&self) -> Result<String, Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.freedesktop.DBus.Introspectable".into(), &"Introspect".into(), |_| {
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let xml: String = try!(i.read());
        Ok(xml)
    }
}

pub trait OrgBluezGattCharacteristic1 {
    type Err;
    fn read_value(&self, options: ::std::collections::HashMap<&str, arg::Variant<Box<arg::RefArg>>>) -> Result<Vec<u8>, Self::Err>;
    fn write_value(&self, value: Vec<u8>, options: ::std::collections::HashMap<&str, arg::Variant<Box<arg::RefArg>>>) -> Result<(), Self::Err>;
    fn start_notify(&self) -> Result<(), Self::Err>;
    fn stop_notify(&self) -> Result<(), Self::Err>;
    fn get_uuid(&self) -> Result<String, Self::Err>;
    fn get_service(&self) -> Result<dbus::Path<'static>, Self::Err>;
    fn get_value(&self) -> Result<Vec<u8>, Self::Err>;
    fn get_notifying(&self) -> Result<bool, Self::Err>;
    fn get_flags(&self) -> Result<Vec<String>, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgBluezGattCharacteristic1 for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn read_value(&self, options: ::std::collections::HashMap<&str, arg::Variant<Box<arg::RefArg>>>) -> Result<Vec<u8>, Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.bluez.GattCharacteristic1".into(), &"ReadValue".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(options);
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let value: Vec<u8> = try!(i.read());
        Ok(value)
    }

    fn write_value(&self, value: Vec<u8>, options: ::std::collections::HashMap<&str, arg::Variant<Box<arg::RefArg>>>) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.bluez.GattCharacteristic1".into(), &"WriteValue".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(value);
            i.append(options);
        }));
        try!(m.as_result());
        Ok(())
    }

    fn start_notify(&self) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.bluez.GattCharacteristic1".into(), &"StartNotify".into(), |_| {
        }));
        try!(m.as_result());
        Ok(())
    }

    fn stop_notify(&self) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.bluez.GattCharacteristic1".into(), &"StopNotify".into(), |_| {
        }));
        try!(m.as_result());
        Ok(())
    }

    fn get_uuid(&self) -> Result<String, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.bluez.GattCharacteristic1", "UUID")
    }

    fn get_service(&self) -> Result<dbus::Path<'static>, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.bluez.GattCharacteristic1", "Service")
    }

    fn get_value(&self) -> Result<Vec<u8>, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.bluez.GattCharacteristic1", "Value")
    }

    fn get_notifying(&self) -> Result<bool, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.bluez.GattCharacteristic1", "Notifying")
    }

    fn get_flags(&self) -> Result<Vec<String>, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.bluez.GattCharacteristic1", "Flags")
    }
}

pub trait OrgFreedesktopDBusProperties {
    type Err;
    fn get(&self, interface: &str, name: &str) -> Result<arg::Variant<Box<arg::RefArg>>, Self::Err>;
    fn set(&self, interface: &str, name: &str, value: arg::Variant<Box<arg::RefArg>>) -> Result<(), Self::Err>;
    fn get_all(&self, interface: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<arg::RefArg>>>, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgFreedesktopDBusProperties for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn get(&self, interface: &str, name: &str) -> Result<arg::Variant<Box<arg::RefArg>>, Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"Get".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface);
            i.append(name);
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let value: arg::Variant<Box<arg::RefArg>> = try!(i.read());
        Ok(value)
    }

    fn set(&self, interface: &str, name: &str, value: arg::Variant<Box<arg::RefArg>>) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"Set".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface);
            i.append(name);
            i.append(value);
        }));
        try!(m.as_result());
        Ok(())
    }

    fn get_all(&self, interface: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<arg::RefArg>>>, Self::Err> {
        let mut m = try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"GetAll".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface);
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let properties: ::std::collections::HashMap<String, arg::Variant<Box<arg::RefArg>>> = try!(i.read());
        Ok(properties)
    }
}

#[derive(Debug, Default)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface: String,
    pub changed_properties: ::std::collections::HashMap<String, arg::Variant<Box<arg::RefArg>>>,
    pub invalidated_properties: Vec<String>,
}

impl dbus::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
    fn append(&self, i: &mut arg::IterAppend) {
        (&self.interface as &arg::RefArg).append(i);
        (&self.changed_properties as &arg::RefArg).append(i);
        (&self.invalidated_properties as &arg::RefArg).append(i);
    }
    fn get(&mut self, i: &mut arg::Iter) -> Result<(), arg::TypeMismatchError> {
        self.interface = try!(i.read());
        self.changed_properties = try!(i.read());
        self.invalidated_properties = try!(i.read());
        Ok(())
    }
}
